### ISSUE TITLE
Add Check Conflicts Workflow

### ISSUE THREAD

**Issue by Xlinka** [Yellow-Dog-Man/Elements.Quantity#4]
Add a check conflicts YML workflow and add a conflict tag to the user pull request
example.

```
name: 'Check for merge conflicts'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@v2.0
        with:
          CONFLICT_LABEL_NAME: "Has Conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
}
```

just realised i could just make a PR for this.
